<a href="https://colab.research.google.com/github/bhoomikanaidu1007/PFBA/blob/main/Practice_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df = pd.read_csv('cleaned_sales.csv')

In [3]:
df.shape

(970, 11)

In [7]:
df.groupby('Product_Category')['Revenue'].sum()

Product_Category
Books               433468.01
Clothing           1564597.81
Electronics       17871743.65
Home & Kitchen     4227285.06
Sports             2234104.72
Name: Revenue, dtype: float64

In [8]:
df.groupby('Region')['Revenue'].mean()

Region
East     23431.874244
North    31850.227479
South    27395.947119
West     25963.521474
Name: Revenue, dtype: float64

In [9]:
df.groupby('Region')['Revenue'].count()

Region
East     238
North    238
South    243
West     251
Name: Revenue, dtype: int64

In [10]:
category_summary = (
df.groupby('Product_Category')['Revenue']
.agg(['sum', 'mean', 'count'])
.rename(columns={
'sum' : 'Total Revenue (₹)',
'mean' : 'Avg Order Value (₹)',
'count' : 'No. of Orders'
})
.sort_values('Total Revenue (₹)', ascending=False)
.round(2)
)
print(category_summary)

                  Total Revenue (₹)  Avg Order Value (₹)  No. of Orders
Product_Category
Electronics             17871743.65             79784.57            224
Home & Kitchen           4227285.06             22366.59            189
Sports                   2234104.72             12551.15            178
Clothing                 1564597.81              8191.61            191
Books                     433468.01              2305.68            188

In [21]:
category_summary['Revenue Share (%)'] = (
category_summary['Total Revenue (₹)']
/ category_summary['Total Revenue (₹)'].sum()
* 100
).round(2)
print (category_summary)

                  Total Revenue (₹)  Avg Order Value (₹)  No. of Orders  \
Product_Category
Electronics             17871743.65             79784.57            224
Home & Kitchen           4227285.06             22366.59            189
Sports                   2234104.72             12551.15            178
Clothing                 1564597.81              8191.61            191
Books                     433468.01              2305.68            188

                  Revenue Share (%)
Product_Category
Electronics                   67.87
Home & Kitchen                16.05
Sports                         8.48
Clothing                       5.94
Books                          1.65

In [23]:
monthly = (
df.groupby(['Month', 'Month_Name'])['Revenue']
.sum()
.reset_index() # ← brings Month and Month_Name back as regular columns
.sort_values('Month') # sort chronologically
)
print(category_summary)

                  Total Revenue (₹)  Avg Order Value (₹)  No. of Orders  \
Product_Category
Electronics             17871743.65             79784.57            224
Home & Kitchen           4227285.06             22366.59            189
Sports                   2234104.72             12551.15            178
Clothing                 1564597.81              8191.61            191
Books                     433468.01              2305.68            188

                  Revenue Share (%)
Product_Category
Electronics                   67.87
Home & Kitchen                16.05
Sports                         8.48
Clothing                       5.94
Books                          1.65

In [19]:
# Row with highest revenue
peak = monthly.loc[monthly['Revenue'].idxmax()]
print(f"Best month : {peak['Month_Name']} → ₹{peak['Revenue']:,.2f}")

Best month : Jan → ₹2,722,578.85

In [20]:
# Row with lowest revenue
worst = monthly.loc[monthly['Revenue'].idxmin()]
print(f"Worst month: {worst['Month_Name']} → ₹{worst['Revenue']:,.2f}")

Worst month: Sep → ₹1,729,339.72

Day 6