<a href="https://colab.research.google.com/github/bhoomikanaidu1007/PFBA/blob/main/Project_1_Python_sales_analyzer_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
# below files / code will be based on project 1 e-commerce

In [20]:
# importing pandas / module to my python interpreter - language processor.
# exel in py
import pandas as pd  #pd ka mtlab pandas ka shortform
import matplotlib.pyplot as plt            # Data visualization
import matplotlib.ticker as mticker        # Formatting chart axes

In [21]:
df = pd.read_csv('sales_data_raw.csv')

In [22]:
df.shape

(1050, 8)

In [23]:
df_clean = pd.read_csv( 'cleaned_sales.csv')

In [24]:
df_clean.shape

(970, 11)

In [25]:
df.describe()

          Quantity    Unit_Price    Discount
count  1050.000000   1020.000000  965.000000
mean      2.977143   9639.630010    7.145078
std       1.420083  12243.319571    7.422468
min       1.000000    203.220000    0.000000
25%       2.000000   1440.300000    0.000000
50%       3.000000   4310.250000    5.000000
75%       4.000000  11470.990000   15.000000
max       5.000000  49930.450000   20.000000

In [26]:
df.head()

,Order_ID,Order_Date,Customer_Name,Product_Category,Quantity,Unit_Price,Discount,Region
0,ORD-10524,2024-05-09,Sneha Kumar,Books,5,592.79,20.0,West
1,ORD-10254,2024-07-04,Arjun Verma,Clothing,2,1046.13,20.0,South
2,ORD-10832,2024-06-08,Rahul Mishra,Electronics,1,43165.58,0.0,West
3,ORD-10343,2024-07-30,Amit Mishra,Electronics,2,15414.50,0.0,South
4,ORD-10601,2024-11-12,Arjun Kumar,Clothing,1,4984.84,0.0,East

In [27]:
df_clean.head()

,Order_ID,Order_Date,Customer_Name,Product_Category,Quantity,Unit_Price,Discount,Region,Revenue,Month,Month_Name
0,ORD-10524,2024-05-09,Sneha Kumar,Books,5,592.79,20.0,West,2371.16,5,May
1,ORD-10254,2024-07-04,Arjun Verma,Clothing,2,1046.13,20.0,South,1673.81,7,Jul
2,ORD-10832,2024-06-08,Rahul Mishra,Electronics,1,43165.58,0.0,West,43165.58,6,Jun
3,ORD-10343,2024-07-30,Amit Mishra,Electronics,2,15414.50,0.0,South,30829.00,7,Jul
4,ORD-10601,2024-11-12,Arjun Kumar,Clothing,1,4984.84,0.0,East,4984.84,11,Nov

In [28]:
df_clean.describe()

         Quantity    Unit_Price    Discount        Revenue       Month
count  970.000000    970.000000  970.000000     970.000000  970.000000
mean     2.988660   9726.460412    6.432990   27145.566237    6.727835
std      1.423986  12344.374455    7.343703   40771.105294    3.485211
min      1.000000    203.220000    0.000000     172.740000    1.000000
25%      2.000000   1452.135000    0.000000    3670.685000    4.000000
50%      3.000000   4310.250000    5.000000   11040.415000    7.000000
75%      4.000000  11741.735000   10.000000   29931.910000   10.000000
max      5.000000  49930.450000   20.000000  233380.800000   12.000000

# Task 1 Data Loading & Inspecting

Objective: Load the CSV file and understand its structure before touching any data.

🔑 Business Rule: Never modify raw data directly. Always load it into a DataFrame first and inspect it thoroughly. A senior analyst always asks:

How many rows and columns do I have?
What are the data types?
Where are the missing values?
Are there duplicates?

In [31]:
# ── Step 1a: Load the CSV ─────────────────────────────────────────────────────
df = pd.read_csv('sales_data_raw.csv')

print('=' * 55)
print('  DATASET LOADED SUCCESSFULLY')
print('=' * 55)
print(f'  Rows    : {df.shape[0]:,}')
print(f'  Columns : {df.shape[1]}')
print('=' * 55)

=======================================================
  DATASET LOADED SUCCESSFULLY
=======================================================
  Rows    : 1,050
  Columns : 8
=======================================================

In [32]:
# ── Step 1b: Preview the first 5 rows ────────────────────────────────────────
# head() shows the top rows — like opening the file and glancing at it
print('--- First 5 rows of the dataset ---')
df.head()

--- First 5 rows of the dataset ---

,Order_ID,Order_Date,Customer_Name,Product_Category,Quantity,Unit_Price,Discount,Region
0,ORD-10524,2024-05-09,Sneha Kumar,Books,5,592.79,20.0,West
1,ORD-10254,2024-07-04,Arjun Verma,Clothing,2,1046.13,20.0,South
2,ORD-10832,2024-06-08,Rahul Mishra,Electronics,1,43165.58,0.0,West
3,ORD-10343,2024-07-30,Amit Mishra,Electronics,2,15414.50,0.0,South
4,ORD-10601,2024-11-12,Arjun Kumar,Clothing,1,4984.84,0.0,East

In [33]:
# ── Step 1c: Check data types and non-null counts ─────────────────────────────
# info() tells us the data type of each column and how many non-null values exist
# Non-null count < total rows  →  that column has MISSING VALUES
print('--- Dataset Information (Data Types & Missing Value Check) ---')
df.info()

--- Dataset Information (Data Types & Missing Value Check) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          1050 non-null   object
 1   Order_Date        1050 non-null   object
 2   Customer_Name     999 non-null    object
 3   Product_Category  1050 non-null   object
 4   Quantity          1050 non-null   int64
 5   Unit_Price        1020 non-null   float64
 6   Discount          965 non-null    float64
 7   Region            1050 non-null   object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.8+ KB

In [34]:
# ── Step 1d: Descriptive statistics ──────────────────────────────────────────
# describe() gives us count, mean, min, max for numeric columns
# This is a quick 'health check' for the numbers
print('--- Descriptive Statistics ---')
df.describe()

--- Descriptive Statistics ---

          Quantity    Unit_Price    Discount
count  1050.000000   1020.000000  965.000000
mean      2.977143   9639.630010    7.145078
std       1.420083  12243.319571    7.422468
min       1.000000    203.220000    0.000000
25%       2.000000   1440.300000    0.000000
50%       3.000000   4310.250000    5.000000
75%       4.000000  11470.990000   15.000000
max       5.000000  49930.450000   20.000000

In [35]:
# ── Step 1e: Count missing values per column ──────────────────────────────────
# isnull() returns True/False for each cell → .sum() counts the Trues per column
missing_counts = df.isnull().sum()
missing_pct    = (df.isnull().sum() / len(df) * 100).round(2)

missing_summary = pd.DataFrame({
    'Missing Count'  : missing_counts,
    'Missing %'      : missing_pct
}).query('`Missing Count` > 0')   # show only columns that have missing values

print('--- Missing Values Summary ---')
print(missing_summary.to_string())
print()
print(f'Duplicate rows found: {df.duplicated().sum()}')

--- Missing Values Summary ---
               Missing Count  Missing %
Customer_Name             51       4.86
Unit_Price                30       2.86
Discount                  85       8.10

Duplicate rows found: 50

---
## 🧹 Task 2 — Data Cleaning

**Objective:** Fix all data quality issues before any analysis.

### Cleaning Rules (Business Decisions)
| Issue | Column | Action | Why |
|-------|--------|--------|-----|
| Missing values | `Unit_Price` | **Drop the row** | We cannot calculate revenue without a price |
| Missing values | `Customer_Name` | **Fill with `"Unknown"`** | Orders are still valid; customer is just anonymous |
| Missing values | `Discount` | **Fill with `0`** | No discount info = no discount was applied |
| Duplicate rows | All columns | **Drop duplicates** | Same order appearing twice inflates revenue figures |

> 💡 **Key Insight:** Data cleaning decisions are **business decisions**, not just technical ones.
> Always justify *why* you chose to drop vs. fill.

In [36]:
# ── Step 2: Data Cleaning ─────────────────────────────────────────────────────

rows_before = len(df)
print(f'Rows BEFORE cleaning: {rows_before:,}')
print('-' * 40)

# 2a. Drop rows where Unit_Price is missing (cannot calculate revenue)
df = df.dropna(subset=['Unit_Price'])
print(f'After dropping missing Unit_Price  : {len(df):,} rows  (-{rows_before - len(df)} rows dropped)')

# 2b. Fill missing Customer_Name with 'Unknown'
missing_names = df['Customer_Name'].isnull().sum()
df['Customer_Name'] = df['Customer_Name'].fillna('Unknown')
print(f'Customer_Name  → filled {missing_names} missing values with "Unknown"')

# 2c. Fill missing Discount with 0 (no discount info = no discount)
missing_disc = df['Discount'].isnull().sum()
df['Discount'] = df['Discount'].fillna(0)
print(f'Discount       → filled {missing_disc} missing values with 0')

# 2d. Remove duplicate rows
before_dedup = len(df)
df = df.drop_duplicates()
print(f'Duplicates     → removed {before_dedup - len(df)} duplicate rows')

print('-' * 40)
print(f'Rows AFTER  cleaning: {len(df):,}')
print()

# Verify: no more missing values
remaining_nulls = df.isnull().sum().sum()
print(f'✅ Remaining missing values: {remaining_nulls}  ← should be 0')

Rows BEFORE cleaning: 1,050
----------------------------------------
After dropping missing Unit_Price  : 1,020 rows  (-30 rows dropped)
Customer_Name  → filled 51 missing values with "Unknown"
Discount       → filled 83 missing values with 0
Duplicates     → removed 50 duplicate rows
----------------------------------------
Rows AFTER  cleaning: 970

✅ Remaining missing values: 0  ← should be 0

---
## ⚙️ Task 3 — Feature Engineering

**Objective:** Create new columns that unlock deeper business insights.

Feature Engineering means **creating new, useful columns from existing data**.
We will create two new columns:
1. **`Revenue`** — the actual money earned per order (after discount)
2. **`Month`** — extracted from `Order_Date` to enable monthly trend analysis

> 💡 **Why Revenue and not just Unit_Price?**
> A ₹10,000 order with a 20% discount only generates ₹8,000 in actual revenue.
> Using Unit_Price alone would **overstate** the company's earnings.

In [37]:
# ── Step 3: Feature Engineering ───────────────────────────────────────────────

# 3a. Convert Order_Date from string to proper datetime format
#     pd.to_datetime() lets Python understand dates (not just text)
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
print(f'Order_Date dtype after conversion: {df["Order_Date"].dtype}  ✅')

# 3b. Create Revenue column
#     Formula: Revenue = Quantity × Unit_Price × (1 - Discount/100)
#     The (1 - Discount/100) part applies the discount percentage
df['Revenue'] = df['Quantity'] * df['Unit_Price'] * (1 - df['Discount'] / 100)
df['Revenue'] = df['Revenue'].round(2)

# 3c. Extract Month number (1=Jan, 2=Feb, ... 12=Dec) from Order_Date
df['Month'] = df['Order_Date'].dt.month

# 3d. Create a Month Name column for readable chart labels
month_names = {1:'Jan', 2:'Feb', 3:'Mar', 4:'Apr', 5:'May', 6:'Jun',
               7:'Jul', 8:'Aug', 9:'Sep', 10:'Oct', 11:'Nov', 12:'Dec'}
df['Month_Name'] = df['Month'].map(month_names)

print()
print('--- Preview with new columns ---')
df[['Order_ID', 'Order_Date', 'Quantity', 'Unit_Price', 'Discount', 'Revenue', 'Month', 'Month_Name']].head(8)

Order_Date dtype after conversion: datetime64[ns]  ✅

--- Preview with new columns ---

,Order_ID,Order_Date,Quantity,Unit_Price,Discount,Revenue,Month,Month_Name
0,ORD-10524,2024-05-09,5,592.79,20.0,2371.16,5,May
1,ORD-10254,2024-07-04,2,1046.13,20.0,1673.81,7,Jul
2,ORD-10832,2024-06-08,1,43165.58,0.0,43165.58,6,Jun
3,ORD-10343,2024-07-30,2,15414.50,0.0,30829.00,7,Jul
4,ORD-10601,2024-11-12,1,4984.84,0.0,4984.84,11,Nov
5,ORD-10559,2024-03-11,3,12673.05,5.0,36118.19,3,Mar
6,ORD-10316,2024-08-04,1,7869.20,0.0,7869.20,8,Aug
7,ORD-10358,2024-01-16,4,11926.38,5.0,45320.24,1,Jan

In [38]:
# ── Quick Revenue Sanity Check ────────────────────────────────────────────────
total_revenue = df['Revenue'].sum()
avg_order_val = df['Revenue'].mean()
max_order_val = df['Revenue'].max()

print('📊 Revenue Overview')
print('=' * 40)
print(f'  Total Annual Revenue  : ₹{total_revenue:>15,.2f}')
print(f'  Average Order Value   : ₹{avg_order_val:>15,.2f}')
print(f'  Largest Single Order  : ₹{max_order_val:>15,.2f}')
print(f'  Total Orders Analyzed : {len(df):>15,}')
print('=' * 40)

📊 Revenue Overview
========================================
  Total Annual Revenue  : ₹  26,331,199.25
  Average Order Value   : ₹      27,145.57
  Largest Single Order  : ₹     233,380.80
  Total Orders Analyzed :             970
========================================