<a href="https://colab.research.google.com/github/bhoomikanaidu1007/PFBA/blob/main/Project_1_Python_sales_analyzer_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# below files / code will be based on project 1 e-commerce

In [10]:
# importing pandas / module to my python interpreter - language processor.
# exel in py
import pandas as pd  #pd ka mtlab pandas ka shortform

In [11]:
df = pd.read_csv('sales_data_raw.csv')

In [12]:
df.shape

(1050, 8)

In [7]:
df_clean = pd.read_csv( 'cleaned_sales.csv')

In [8]:
df_clean.shape

(970, 11)

In [17]:
df.describe()

          Quantity    Unit_Price    Discount
count  1050.000000   1020.000000  965.000000
mean      2.977143   9639.630010    7.145078
std       1.420083  12243.319571    7.422468
min       1.000000    203.220000    0.000000
25%       2.000000   1440.300000    0.000000
50%       3.000000   4310.250000    5.000000
75%       4.000000  11470.990000   15.000000
max       5.000000  49930.450000   20.000000

In [14]:
df.head()

,Order_ID,Order_Date,Customer_Name,Product_Category,Quantity,Unit_Price,Discount,Region
0,ORD-10524,2024-05-09,Sneha Kumar,Books,5,592.79,20.0,West
1,ORD-10254,2024-07-04,Arjun Verma,Clothing,2,1046.13,20.0,South
2,ORD-10832,2024-06-08,Rahul Mishra,Electronics,1,43165.58,0.0,West
3,ORD-10343,2024-07-30,Amit Mishra,Electronics,2,15414.50,0.0,South
4,ORD-10601,2024-11-12,Arjun Kumar,Clothing,1,4984.84,0.0,East

In [15]:
df_clean.head()

,Order_ID,Order_Date,Customer_Name,Product_Category,Quantity,Unit_Price,Discount,Region,Revenue,Month,Month_Name
0,ORD-10524,2024-05-09,Sneha Kumar,Books,5,592.79,20.0,West,2371.16,5,May
1,ORD-10254,2024-07-04,Arjun Verma,Clothing,2,1046.13,20.0,South,1673.81,7,Jul
2,ORD-10832,2024-06-08,Rahul Mishra,Electronics,1,43165.58,0.0,West,43165.58,6,Jun
3,ORD-10343,2024-07-30,Amit Mishra,Electronics,2,15414.50,0.0,South,30829.00,7,Jul
4,ORD-10601,2024-11-12,Arjun Kumar,Clothing,1,4984.84,0.0,East,4984.84,11,Nov

In [16]:
df_clean.describe()

         Quantity    Unit_Price    Discount        Revenue       Month
count  970.000000    970.000000  970.000000     970.000000  970.000000
mean     2.988660   9726.460412    6.432990   27145.566237    6.727835
std      1.423986  12344.374455    7.343703   40771.105294    3.485211
min      1.000000    203.220000    0.000000     172.740000    1.000000
25%      2.000000   1452.135000    0.000000    3670.685000    4.000000
50%      3.000000   4310.250000    5.000000   11040.415000    7.000000
75%      4.000000  11741.735000   10.000000   29931.910000   10.000000
max      5.000000  49930.450000   20.000000  233380.800000   12.000000